export enum EntityType {
  // Core
  ORGANIZATION = 'ORGANIZATION',
  USER = 'USER',
  
  // Person/Party
  PERSON = 'PERSON',
  CLIENT = 'CLIENT',
  SUPPLIER = 'SUPPLIER',
  WORKER = 'WORKER',
  FARM_OWNER = 'FARM_OWNER',
  
  // Farm/Property
  FARM = 'FARM',
  RURAL_PROPERTY = 'RURAL_PROPERTY',
  FARM_RURAL_PROPERTY = 'FARM_RURAL_PROPERTY',
  LAND_REGISTRY = 'LAND_REGISTRY',
  PROPERTY_OWNERSHIP = 'PROPERTY_OWNERSHIP',
  STATE_REGISTRATION = 'STATE_REGISTRATION',
  STATE_REGISTRATION_PARTICIPANT = 'STATE_REGISTRATION_PARTICIPANT',
  STATE_REGISTRATION_LAND_REGISTRY = 'STATE_REGISTRATION_LAND_REGISTRY',
  
  // Field/Season
  FIELD = 'FIELD',
  FIELD_SEASON = 'FIELD_SEASON',
  SEASON = 'SEASON',
  WORK_LOCATION_TYPE = 'WORK_LOCATION_TYPE',
  
  // Financial/Accounting
  BANK_ACCOUNT = 'BANK_ACCOUNT',
  COST_CENTER = 'COST_CENTER',
  COST_CENTER_CATEGORY = 'COST_CENTER_CATEGORY',
  COST_CENTER_KIND_CATEGORY = 'COST_CENTER_KIND_CATEGORY',
  MANAGEMENT_ACCOUNT = 'MANAGEMENT_ACCOUNT',
  MANAGEMENT_ACCOUNT_COST_CENTER_TYPE = 'MANAGEMENT_ACCOUNT_COST_CENTER_TYPE',
  
  // Invoice
  INVOICE = 'INVOICE',
  INVOICE_ITEM = 'INVOICE_ITEM',
  INVOICE_FINANCIAL = 'INVOICE_FINANCIAL',
  INVOICE_FINANCIALS_TYPE = 'INVOICE_FINANCIALS_TYPE',
  INVOICE_RECEIPT = 'INVOICE_RECEIPT',
  INVOICE_RECEIPT_ITEM = 'INVOICE_RECEIPT_ITEM',
  INVOICE_SHIPMENT = 'INVOICE_SHIPMENT',
  INVOICE_SHIPMENT_ITEM = 'INVOICE_SHIPMENT_ITEM',
  DOCUMENT_TYPE = 'DOCUMENT_TYPE',
  
  // Asset/Machine
  ASSET = 'ASSET',
  MACHINE = 'MACHINE',
  MACHINE_TYPE = 'MACHINE_TYPE',
  
  // Inventory/Product
  ITEM = 'ITEM',
  PRODUCT = 'PRODUCT',
  STOCK_MOVEMENT = 'STOCK_MOVEMENT',
  STOCK_MOVEMENT_TYPE = 'STOCK_MOVEMENT_TYPE',
  
  // Reference/Configuration
  ACTIVITY_TYPE = 'ACTIVITY_TYPE',
  OPERATION = 'OPERATION',
  OPERATION_RECORD = 'OPERATION_RECORD',
  UNIT_OF_MEASURE = 'UNIT_OF_MEASURE',
  UNIT_OF_MEASURE_CONVERSION = 'UNIT_OF_MEASURE_CONVERSION',
}
